### ISSUE TITLE
JS EOF Error when sending long JS string to scrapy splash

### ISSUE THREAD

**Issue by fbuchinger** [scrapy-plugins/scrapy-splash#139]
The following splash/lua script concatenates all style sheets of the loaded webpage to a string and returns in. It runs fine the splash demopage (localhost:8050):
```lua
function main(splash, args)
  splash.images_enabled = false
  local get_stylesheet_rules = splash:jsfunc([[
  function () {
       var cssout = [];
       for (var i = 0; i < document.styleSheets.length; i++){
        var curStyleSheet = document.styleSheets[i];
            for (var j = 0; j < curStyleSheet.cssRules.length; j++){
                cssout.push(curStyleSheet.cssRules[j].cssText);
            }
       }
       return cssout.join('\n');
    }
  ]])
  splash:go(args.url)
  splash:wait(0.5)
  return get_stylesheet_rules ()
end
```
When using the same code in scrapy-splash, my log gets filled up with the following errors:

`
2017-09-17 23:10:41 [scrapy_splash.middleware] WARNING: Bad request to Splash: {u'info': {u'js_error': u'SyntaxError: Unexpected EOF', u'js_error_type': u'SyntaxError', u'js_error_message': u'Unexpected EOF', u'error': u"error during JS function call: 'SyntaxError: Unexpected EOF'", u'message': u"error during JS function call: 'SyntaxError: Unexpected EOF'", u'type': u'JS_ERROR'}, u'type': u'ScriptError', u'description': u'Error happened while executing Lua script', u'error': 400}
`

and later

`
2017-09-17 23:10:41 [scrapy] DEBUG: Ignoring response <400 <webpageurl/>: HTTP status code is not handled or not allowed
`

Any hints?

**Comment by kmike** [comment]
I haven't tried it, but it may be a string formatting issue. Are you defining this script in Python code as a string? "\n" can be a part of your script expanded to CRLF, not a constant used in JS, and JS doesn't have multiline string constants. There is another issue with `\n` - even if Lua source code really contains `'\n'`, JS code is defined as a string constant, so `\n` will be replaced by its code by Lua when creating this string constant.

**Comment by fbuchinger** [comment]
Hi! Yes, the script was defined in a python string - I followed a similar approach with another lua script and didn't experience problems. What would be the exact workaround? Replacing all newlines with \n?

**Comment by kmike** [comment]
Add `r` before the string constant.

To clarify, what the problem is. Let's say you create a Lua script in Python using this code:

```py
script = """x = [[ window.foo='\n' ]]"""
```

This is what you get (it is just how Python works):

```
In [5]: print(script)
x = [[ window.foo='
' ]]
```

So, you need to prevent  "\n" from converting to a new line. You can do it by escaping, by not defining a script as a string constant, or by using raw strings:

```
In [6]: script = r"""x = [[ window.foo='\n' ]]"""
In [7]: print(script)
x = [[ window.foo='\n' ]]
```

Ok, this is better now. Now we may have exactly the same issue in Lua code: x is a string constant, and Lua handles `\n` the same way as Python, replacing it with a new line. But we don't have it, because Lua only replaces "\n" in strings defined using quotes; strings defined using [[ ]] don't interpret escape sequences.
