### ISSUE TITLE
Add support for .click() on non <button> DOM elements.

### ISSUE THREAD

**Issue by wocoburguesa** [scrapy-plugins/scrapy-splash#27]
I ran into this issue while trying to interact with a page that had a `<div>` which I needed to click to load additional data. I tried doing a Lua script that loaded jQuery and then clicked the element like so:

``` lua
assert(splash:runjs("$(#element-id).click()"))
```

but it kept returning the same original html with no modifications. Took me a while to figure this out.

For anyone running into this issue, using basic javascript to simulate the click worked for me:

``` lua
local fireClick = splash:jsfunc([[
    function() {{
      var c = document.createEvent("MouseEvents"),
        el = document.getElementsByClassName(
          //some selector
        )[0];

        c.initMouseEvent("click",true,true,window,0,0,0,0,0,false,false,false,false,0,null);
        el.dispatchEvent(c);
    }}
]])

fireClick()
```

**Comment by kmike** [comment]
Splash master is using qt5 now; this works for me with latest Splash:

``` lua
function main(splash)
  local url = "http://reddit.com/" -- splash.args.url
  assert(splash:go(url))
  assert(splash:wait(0.5))
  assert(splash:runjs("$('a')[1].click()"))
  splash:wait(0.5)
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

`$("foo").click()` likely won't work because of jQuery - see http://stackoverflow.com/questions/1694595/can-i-call-jquery-click-to-follow-an-a-link-if-i-havent-bound-an-event-hand.

See also: https://github.com/scrapinghub/splash/issues/200#issuecomment-112552839

+1 to add createEvent helpers to Splash.

It is not a scrapy-splash issue; I'm closing it in favor of https://github.com/scrapinghub/splash/issues/200.

**Comment by wocoburguesa** [comment]
Thanks for the additional input!
