### ISSUE TITLE
Cannot scrape recursively with scrapyjs

### ISSUE THREAD

**Issue by DionisAI** [scrapy-plugins/scrapy-splash#32]
I try to use two yields:

``` py
def parse(self, response):
  ...
  yield scrapy.Request(url, self.parse_item, meta={'splash': ...})

def parse_item(self, response):
  ...
  yield scrapy.Request(url, self.parse_list, meta={'splash': ...})
```

And I got

> Traceback (most recent call last):
>   File "/Users/hurryhx/Library/Python/2.7/lib/python/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
>     yield next(it)
> GeneratorExit
> Exception RuntimeError: 'generator ignored GeneratorExit' in <generator object iter_errback at 0x10a1c6c80> ignored
> Unhandled error in Deferred:
> 2016-01-29 01:02:18 [twisted] CRITICAL: Unhandled error in Deferred:

But this code could work without splash. (Of course cannot deal with JavaScript)

How to fix it?

**Comment by rlucca** [comment]
It is returning a fail inside the generator, it is not being treat possibly because you doesnt specified an errback function. Just try change:
`   yield scrapy.Request(url, self.parse_item, meta={'splash': ...})`
To:
`yield scrapy.Request(url, self.parse_item, errback=self.parse_error, meta={'splash': ...})`

This should call your self.parse_error.

Edit: because forget to put the code tags.

**Comment by Gallaecio** [comment]
@hurryhx Did it fix your issue?
