### ISSUE TITLE
set headers/cookies for the outgoing GET requests.

### ISSUE THREAD

**Issue by cduongvn** [scrapy-plugins/scrapy-splash#44]
Hi, I got a question.

Given a spider has cookies by previous requests, this request `scrapy.Request(url, callback=self.parse_result)` will be sent with headers/cookies included. When using splash to render the page, I want it to use these headers as well. Is it currently supported?

I fount that there is an argument `headers` for endpoint: `render.html`, but this option is only supported for `application/json` POST requests. How about GET requests?

Thanks in advance,
Canh

**Comment by cduongvn** [comment]
I just found that original HTTP headers (including cookies) are not respected.
https://github.com/scrapy-plugins/scrapy-splash/blob/master/scrapyjs/middleware.py#L108

**Comment by kmike** [comment]
Hey @nautilus28,

There are two types of requests: requests sent from Scrapy to Splash and requests sent from Splash to remote websites. With scrapy-splash Scrapy->Splash requests are always `application/json` POST requests. It means that to send custom headers to remote website it is enough to add 'headers' key to `request['meta']['splash']['args']`.

But that's true setting cookie headers is not straightforward because to set them you need to get them first, and it is not easy.

**Comment by cduongvn** [comment]
Thanks for your detailed explanation @kmike

**Comment by kmike** [comment]
Hey @nautilus28,

Please check the updated README; there are utilities to handle cookies and headers in scrapy-splash master branch.
