### ISSUE TITLE
Publish package as scrapy-splash on PyPI

### ISSUE THREAD

**Issue by redapple** [scrapy-plugins/scrapy-splash#46]
Replacing [`scrapyjs`](https://pypi.python.org/pypi/scrapyjs)
Repository was already renamed.

**Comment by kmike** [comment]
@redapple I've released scrapyjs 0.2 in order to have a 'stable' release which is unlikely to break anything. I think it makes sense to rename project to scrapy-splash (and package to scrapy_splash?) after https://github.com/scrapy-plugins/scrapy-splash/pull/45 merge - these changes are much more risky, so that's good users won't be upgraded automatically.

**Comment by kmike** [comment]
Done!
