### ISSUE TITLE
Removed cookie handling

### ISSUE THREAD

**Issue by lopuhin** [scrapy-plugins/scrapy-splash#52]
I think there's a problem with removing cookies: if we get them via `splash:get_cookies`, then if the cookie is set to an empty string (as a result of logout), it will be absent in `response.data['cookies']`, and as a result, they will stay in the `cookiejar` in `SplashCookiesMiddleware`: https://github.com/lopuhin/scrapy-splash/commit/478db5d729adb027c43d72915c98aacb75bbbc64

I see three ways to fix this:
1. if the cookie disappeared from `response.data['cookies']`, remove it from the `cookiejar` too
2. if the cookie disappeared from `response.data['cookies']`, add it to `cookiejar` with an empty string value?
3. get cookies in some other way, for example from `har` log?

Not sure which way is the best. (1) is by far the easiest and looks very logical, but this might be different from what people will expect?

**Comment by kmike** [comment]
Hm, I thought empty cookies stay empty in `splash:get_cookies()` and wrote the code with that assumption. Yeah, we've got a problem here.

I think both (1) and (2) are fine; for a website there is no way to force client to remove a cookie, so empty values is what they send AFAIK. 

For (1) it seems we should compare response.data['cookies'] with request cookies, not with current cookies in cookiejar, because requests to Splash can be sent in parallel.

**Comment by lopuhin** [comment]
Yes, indeed - I always forget about parallel requests. I'll try to implement and test (1) then, thanks!
