### ISSUE TITLE
How can I click <a>  

### ISSUE THREAD

**Issue by bfdcq** [scrapy-plugins/scrapy-splash#77]
url:http(s)://bbs.ngacn.cc/nuke.php?__lib=login&__act=login_ui
`<a id="showcaptchad" href="javascript:void(0)" onclick="showCaptchad(this)">xxxxxxxx</a>
`

```
script = ''' 
function main(splash)
     splash.images_enabled = false
     splash.resource_timeout = 100.0
     splash:autoload('http://code.jquery.com/jquery-2.1.3.min.js')
     assert(splash:go(splash.args.url))
     splash:wait(1)
     splash:runjs("$('#showcaptchad').click()")
     splash:wait(0.5)
     return splash:html()  
end
'''
```

it never works.

but
`document.getElementById("showcaptchad").click()`
worked well.

1.Whether jQuery does not support click <a>.
2.how can I click the link like 
`<a tabindex="-1" href="#J_Reviews" rel="nofollow" hidefocus="true" data-index="1">xxxxxxx<em class="J_ReviewsCount" style="display: inline;">62791</em></a>`
or 
`<a href="?spm=a220o.1000855.0.0.JZj6pP&amp;page=2" data-spm-anchor-id="a220o.1000855.0.0">2</a>`
they don't contain id='xxx' or  name='xxx' .
I can't use 'getElementById()' or 'getElementsByName()'.
what should I do?

**Comment by xchangcheng** [comment]
It's easy if you choose selenium.webdriver to implement a 'click'.

However, if you want to crawl a huge number of pages, it may not work any more. 

I'm trying to crawl thousands of pages, and for each page I may have to 'click next' many times to get the next pages. I have tried three possible webdrivers (chrome, firefox and PhantomJS). All of them are too slow (30s+ to load one page).

That's why I'm considering if scrapy+splash can help me. I'm still digging...

**Comment by kmike** [comment]
Hey,

In Splash 2.1 there is splash:mouse_click method; check an example here: http://splash.readthedocs.io/en/latest/scripting-ref.html#splash-mouse-click

**Comment by kmike** [comment]
regarding JQuery - see http://stackoverflow.com/questions/1694595/can-i-call-jquery-click-to-follow-an-a-link-if-i-havent-bound-an-event-hand

**Comment by xchangcheng** [comment]
Hi, kmike,
Sorry for the delay. Thank you for you quick solution. I will try to figure it out with your suggestions. 

Thanks.
