### ISSUE TITLE
splash's response.request different from that of SplashRequest produced by spider to engine

### ISSUE THREAD

**Issue by dingld** [scrapy-plugins/scrapy-splash#89]
## scrapy_splash does not go with scrapylib.deltafetch

> 1. The deltafetch module actually takes no effect when scrapy_splash is enabled, thus letting go of duplicated request.url already scraped before. 
> 2. It took a while to find out that response.request from scrapy_splash is not the exact copy of the orginal one from spider into engine. It seems that the original request is the instance of SplashRequest, and the request from response is just a modified scrapy.http.Request 
> 3. The following is the (method, url, body) of both requests 
> 
> ```
> the original request from spider (GET, http://www.google.com, b'')
> the request from response.request (POST, http://127.0.0.1:8050/render.html, b'{"headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en", "User-Agent": "Scrapy"\n    }, "url": "http://www.google.com",  "wait": 2}')
> ```
> 
> Is there a way to distinguish the two from input parameters? To use deltafetch middleware together with scrapy_splash, I have to modify the method of generating keys in deltafetch, which is possible but redundant in case of using SplashRequest and scrapy.http.Request in the same spider of the same slot.

**Comment by kmike** [comment]
Hey @dingld,
1. I'm not familiar with deltafetch middleware, but from the code it looks like it can use 'deltafetch_key' meta key instead of request fingerprint (see https://github.com/scrapy-plugins/scrapy-deltafetch/blob/c13554474be4631c3e1d6e2e86c2b0ced86b817a/scrapy_deltafetch/middleware.py#L92). This should fix the issue. You can set it e.g. to request_fingerprint(request):
   
   ```
   request = SplashRequest(url, ...)
   request.meta['deltafetch_key'] = request_fingerprint(request)
   ```
2. Request from response can be just a scrapy.http.Request because of https://github.com/scrapy/scrapy/issues/1890. Are you using disk queues? Even if request class is changed, why is this a problem in your case?
3. Real HTTP request is sent to Splash; it is a POST request to 127.0.0.1:8050. "Original" request is not sent anywhere; it is converted by scrapy-splash in order to render it whrough Splash instead of just downloading.

**Comment by Gallaecio** [comment]
@kmike Maybe we can close this?
